version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: studio_db
    ports:
      - "5432:5432"